version: "3.4"
services:
  posterr-web-api:
    container_name: posterr
    image: foodfacilities-web-api
    build:
      context: ../
      dockerfile: ./src/RadAI.FoodFacilites.WebAPI/Dockerfile
    ports:
      - "5000:80"
      - "5111:443"