version: "3.4"
services:
  foodfacilities-web-api:
    container_name: foodfacilities
    image: foodfacilities-web-api
    build:
      context: ../
      dockerfile: ./src/RadAI.FoodFacilities.WebAPI/Dockerfile
    ports:
      - "5000:80"
      - "5111:443"